vim.opt.backup = false				-- does not create backup file
vim.opt.clipboard="unnamedplus"			-- use system clipboard
vim.opt.conceallevel = 0			-- makes `` visible in markdown files
vim.opt.fileencoding = "utf-8"			-- sets encoding for files
vim.opt.hlsearch = true				-- highlights all matches for search patterns
vim.opt.ignorecase = true			-- ignore case in search patterns
vim.opt.mouse = "a"				    -- allows mouse to be used
vim.opt.pumheight = 10				-- sets pop up menu height
vim.opt.number = true				-- show line numbers
vim.opt.relativenumber = true			-- show hybrid line numbers (Relative except on current line)
vim.opt.showmode = true				-- show mode
vim.opt.showtabline = 2				-- always show tabs
vim.opt.shiftwidth = 4				-- set number of spaces to insert per indentation
vim.opt.tabstop = 4					-- sets tab to give 2 spaces
vim.opt.cursorline = true			-- highlight current line
vim.opt.smartcase = true			-- use smart case
vim.opt.smartindent = true			-- use smart indent
vim.opt.splitbelow = true			-- force all horizontal splits to be done below the current window
vim.opt.splitright = true			-- force all vertical splits to be done to the right of the current window
vim.opt.swapfile = false			-- does not create swapfile
vim.opt.expandtab = true			-- convert tabs to spaces
vim.opt.undofile = true				-- creates persistent undo
vim.opt.scrolloff = 8               -- sets the number of lines 
vim.opt.signcolumn = "yes"          -- Keeps the LSP column present at all times, prevents NVim from rocking back and fourth during normal->insert
vim.opt.winborder = "rounded"       -- Rounds off borders for other windows in vim
vim.opt.autochdir = true            -- Moves working directory to whatever file we open
