return {
    "nvim-treesitter/nvim-treesitter", 
    branch = 'master',
    lazy = false, 
    build = ":TSUpdate",
    config = function()
        local configs = require("nvim-treesitter.configs")
        configs.setup({
            ensure_installed = {
                "c",
                "lua",
                "cpp",
                "python",
                "java",
                "javascript",
                "go",
                "rust",
                "c_sharp",
                "gdscript",
                "make",
                "arduino",
                "asm",
                "bash",
                "cmake",
                "comment",
                "css",
                "csv",
                "diff",
                "desktop",
                "disassembly",
                "dockerfile",
                "fortran",
                "gdshader",
                "git_config",
                "git_rebase",
                "gitattributes",
                "gitcommit",
                "gitignore",
                "haskell",
                "html",
                "htmldjango",
                "http",
                "hyprlang",
                "ini",
                "javadoc",
                "jsdoc",
                "json",
                "json5",
                "jsonnet",
                "kconfig",
                "kotlin",
                "linkerscript",
                "luadoc",
                "markdown",
                "markdown_inline",
                "matlab",
                "meson",
                "objdump",
                "php",
                "powershell",
                "printf",
                "properties",
                "regex",
                "ruby",
                "sql",
                "ssh_config",
                "svelte",
                "sway",
                "tmux",
                "toml",
                "typescript",
                "udev",
                "xml",
                "yaml",
            },
            sync_install = false,
            highlight = { 
                enable = true, 
                disable = {""},
                additional_vim_regex_highlighting = true,
            },
            indent = { 
                enable = true, 
                disable = { "yaml" },
            },
        }) 
    end
}
